#-------------------------
# Profile
#-------------------------
# Create
POST  http://localhost:3333/api/profile/create HTTP/1.1
content-type: application/json

{
          "gender":"girl",
          "photo":"0002.jpeg"
}

###
# Read
GET http://localhost:3333/api/profile/read HTTP/1.1
content-type: application/json



#-------------------------
# User
#-------------------------
###
# Create
POST  http://localhost:3333/api/user/create HTTP/1.1
content-type: application/json

{
    "name":"ゆうし",
    "profile": [{"url":"1"},{"url":"2"}]
}

###
# Read
GET http://localhost:3333/api/user/read HTTP/1.1
content-type: application/json



###
#-------------------------
# りぬ create
#-------------------------
# Create
POST  http://localhost:3333/api/rinu/create HTTP/1.1
content-type: application/json

{
"name":"あいうえお",
"profile":{
    "gender":"men",
    "photo":"0001.jpg"
}
}

#-------------------------
# Question
#-------------------------
###
# Create
POST  http://localhost:3333/api/question/create HTTP/1.1
content-type: application/json

{
"title":"dogs",
"text":"いぬ",
"categories":[{"name":"animals"},{"name":"zoo"}]
}

###
# Read
GET http://localhost:3333/api/question/read HTTP/1.1
content-type: application/json

