#-------------------------
# Profile
#-------------------------
# Create
POST  http://localhost:3333/api/profile/create HTTP/1.1
content-type: application/json

{
"gender":"おとこ",
"photo":"a"
}

###
# Read
GET http://localhost:3333/api/profile/read HTTP/1.1
content-type: application/json



#-------------------------
# User
#-------------------------
###
# Create
POST  http://localhost:3333/api/user/create HTTP/1.1
content-type: application/json

{
"name":"あいうえお",
"profile":{
    "gender":"men",
    "photo":"0001.jpg"
}
}

###
# Read
GET http://localhost:3333/api/user/read HTTP/1.1
content-type: application/json




















































































































































































































